"""
GUI Constants for Visual Novel Patch Manager.
Defines colors, dimensions, display strings, and thumbnail specifications.
Integrates with the SteamOS visual theme system.
"""

from .theme import (
    COLOR_CANVAS,
    COLOR_ELEVATION_1,
    COLOR_ELEVATION_2,
    COLOR_BORDER_2,
    COLOR_ELEVATION_3,
    COLOR_BORDER_FOCUSED,
    COLOR_BORDER_HOVER,
    COLOR_ACCENT_BLUE,
    COLOR_PRIMARY_BLUE,
    COLOR_PRIMARY_HOVER,
    COLOR_ACCENT_GREEN,
    COLOR_ACCENT_GREEN_HOVER,
    COLOR_DANGER_RED,
    COLOR_STATUS_PATCHED,
    COLOR_STATUS_READY,
    COLOR_STATUS_MISSING,
    COLOR_TEXT_PRIMARY,
    COLOR_TEXT_MUTED,
    COLOR_TEXT_DARK,
    POSTER_CARD_SIZE,
    GRID_CARD_BANNER_SIZE,
    LIST_ROW_BANNER_SIZE,
    HERO_BANNER_SIZE,
    CARD_RADIUS,
    MIN_TOUCH_TARGET,
    POSTER_COLUMNS_MIN,
    POSTER_COL_WIDTH,
)

# Display Modes
MODE_LOCAL_DISPLAY = "Local"
MODE_SMB_DISPLAY = "Network"

FILTER_ORDER = ["all", "ready", "patched", "missing", "backup"]
FILTER_LABELS = {
    "all": "All",
    "ready": "Ready",
    "patched": "Patched",
    "missing": "Missing",
    "backup": "Backup",
}
SORT_ORDER = ["A-Z", "Z-A", "Rating"]

# Window Dimensions & Geometry
DEFAULT_GEOMETRY = "1060x680"
STEAM_DECK_GEOMETRY = "1280x800+0+0"
COMPACT_GEOMETRY = "1000x610"

MIN_WIDTH_DEFAULT = 800
MIN_HEIGHT_DEFAULT = 520
MIN_WIDTH_COMPACT = 760
MIN_HEIGHT_COMPACT = 480

# Palette & Surface Colors (SteamOS Dark Slate)
COLOR_BG_BLACK = COLOR_CANVAS
COLOR_SURFACE_DARK = COLOR_ELEVATION_1
COLOR_SURFACE_CARD = COLOR_ELEVATION_2
COLOR_SURFACE_BORDER = COLOR_BORDER_2
COLOR_INPUT_BG = COLOR_ELEVATION_1
COLOR_MODAL_BG = COLOR_ELEVATION_1
COLOR_MODAL_CANVAS = COLOR_CANVAS

# Accent & Button Colors
COLOR_SECONDARY_BTN = COLOR_BORDER_2
COLOR_SECONDARY_BTN_HOVER = COLOR_ELEVATION_3

# Status & Badge Accents
COLOR_STATUS_GREEN = COLOR_STATUS_PATCHED
COLOR_STATUS_YELLOW = COLOR_STATUS_READY
COLOR_STATUS_AMBER = COLOR_STATUS_READY
COLOR_STATUS_RED = COLOR_DANGER_RED
COLOR_STATUS_RED_LIGHT = "#f87171"
COLOR_STATUS_ROSE = COLOR_STATUS_MISSING

# Typography Colors
COLOR_TEXT_WHITE = COLOR_TEXT_PRIMARY
COLOR_TEXT_DARK_MUTED = COLOR_TEXT_DARK

# Badges & Tag Highlights
COLOR_BADGE_ANIMATED = "#c084fc"
COLOR_BADGE_PINK = COLOR_STATUS_MISSING
COLOR_BADGE_SKY = COLOR_ACCENT_BLUE
COLOR_BADGE_PURPLE = "#a855f7"

# Artwork Thumbnail Dimensions
THUMB_SIZE_CAPSULE = POSTER_CARD_SIZE
THUMB_SIZE_HERO = (240, 78)
THUMB_SIZE_LOGO = (200, 112)
THUMB_SIZE_ICON = (80, 80)
THUMB_SIZE_WIDE = (230, 108)

__all__ = [
    "MODE_LOCAL_DISPLAY",
    "MODE_SMB_DISPLAY",
    "DEFAULT_GEOMETRY",
    "STEAM_DECK_GEOMETRY",
    "COMPACT_GEOMETRY",
    "MIN_WIDTH_DEFAULT",
    "MIN_HEIGHT_DEFAULT",
    "MIN_WIDTH_COMPACT",
    "MIN_HEIGHT_COMPACT",
    "COLOR_BG_BLACK",
    "COLOR_SURFACE_DARK",
    "COLOR_SURFACE_CARD",
    "COLOR_SURFACE_BORDER",
    "COLOR_BORDER_FOCUSED",
    "COLOR_BORDER_HOVER",
    "COLOR_INPUT_BG",
    "COLOR_MODAL_BG",
    "COLOR_MODAL_CANVAS",
    "COLOR_PRIMARY_BLUE",
    "COLOR_PRIMARY_HOVER",
    "COLOR_ACCENT_GREEN",
    "COLOR_ACCENT_GREEN_HOVER",
    "COLOR_SECONDARY_BTN",
    "COLOR_SECONDARY_BTN_HOVER",
    "COLOR_STATUS_GREEN",
    "COLOR_STATUS_YELLOW",
    "COLOR_STATUS_AMBER",
    "COLOR_STATUS_RED",
    "COLOR_STATUS_RED_LIGHT",
    "COLOR_STATUS_ROSE",
    "COLOR_TEXT_WHITE",
    "COLOR_TEXT_MUTED",
    "COLOR_TEXT_DARK_MUTED",
    "COLOR_BADGE_ANIMATED",
    "COLOR_BADGE_PINK",
    "COLOR_BADGE_SKY",
    "COLOR_BADGE_PURPLE",
    "THUMB_SIZE_CAPSULE",
    "THUMB_SIZE_HERO",
    "THUMB_SIZE_LOGO",
    "THUMB_SIZE_ICON",
    "THUMB_SIZE_WIDE",
    "GRID_CARD_BANNER_SIZE",
    "LIST_ROW_BANNER_SIZE",
    "HERO_BANNER_SIZE",
    "CARD_RADIUS",
    "MIN_TOUCH_TARGET",
    "POSTER_CARD_SIZE",
    "POSTER_COLUMNS_MIN",
    "POSTER_COL_WIDTH",
]
